Add fields to Email Struct. Handle Mailgun 'event-data'
maartenvanvliet/receivex pull request #77
Opened 2021-12-14 16:58 UTC by cpursley

@maartenvanvliet

I took the liberty (hope that's alright) of adding message_id, event, timestamp and raw params to the Email Struct. These fields are shared by both Mandrill and Mailgun. Also, I expanded upon Mailgun to handle [event-data](https://documentation.mailgun.com/en/latest/api-webhooks.html#webhooks) webhook types.

You may want to manually test a bit. I did expand the Mailgun tests, but these could still be beefier. So far, these Mailgun changes are working well for me in production

This will need a version bump before release (if you accept the PR). Let me know if you'd like me to make any modification.

2021-12-14 19:35 UTC, maartenvanvliet requested changes
Thanks for this!! Couple of small nits and it can be merged :)

If you have more ideas, let me know!

2021-12-14 19:35 UTC, maartenvanvliet commented on lib/receivex/adapters/mailgun.ex
> +  defp from(from), do: parse_address(from)
should the parse_address and related also be moved to the Parsers module?

2021-12-14 19:35 UTC, maartenvanvliet commented on lib/receivex/email.ex
> +          timestamp: DateTime.t(),
```suggestion
          timestamp: DateTime.t() | nil,
```

2021-12-14 19:35 UTC, maartenvanvliet commented on lib/receivex/parsers.ex
> +  def to_datetime(timestamp) when is_float(timestamp) do
do any of the api's return float timestamps? 

I feel we can be more assertive here and raise when it doesn't conform to a timestamp, and stick to either strings or integers.

2021-12-14 19:52 UTC, cpursley commented
Thank for the feedback, I will make those changes.

Yeah, Mailgun sends over a float - at least for `event-data` webhook. So maybe it's best to handle timestamp as a string and let the end user deal with it as they want (and this allows more flexibility).

I will make a mention about the event-data webhook types. I'm actually not sure what the previous/existing Mailgun webhook type is from - if you know, can you point met to the docs?

2021-12-14 20:02 UTC, cpursley commented on lib/receivex/adapters/mailgun.ex
> +  defp valid_webhook_request?(
Yep, hope that is alright. Will do on comment.

2021-12-14 23:06 UTC, cpursley commented
I need to do a bit more testing before this gets merged.

2021-12-15 18:56 UTC, cpursley commented
Okay, this is working pretty well for me.

One catch with the Mailgun event-data webhook is many of the Email Struct values are `nil`. So if you think that is too much divergence from a general-purpose structure - maybe we create different Structs per adapter.

2021-12-22 09:14 UTC, maartenvanvliet approved these changes
thanks! ❤️❤️

I'll see if I can whip up a release in the coming days

2021-12-22 09:14 UTC, merged